"""Initial migration - users, sessions, websites, pageviews

Revision ID: 55ea4a9600a0
Revises: 
Create Date: 2025-10-28 07:10:17.331683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ea4a9600a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_index(op.f('ix_sessions_user_email'), 'sessions', ['user_email'], unique=False)
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('tracking_code', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_tracking_code'), 'websites', ['tracking_code'], unique=True)
    op.create_index(op.f('ix_websites_user_email'), 'websites', ['user_email'], unique=False)
    op.create_table('pageviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pageviews_website_timestamp', 'pageviews', ['website_id', 'timestamp'], unique=False)
    op.create_index('idx_pageviews_website_visitor', 'pageviews', ['website_id', 'visitor_hash'], unique=False)
    op.create_index(op.f('ix_pageviews_browser'), 'pageviews', ['browser'], unique=False)
    op.create_index(op.f('ix_pageviews_country'), 'pageviews', ['country'], unique=False)
    op.create_index(op.f('ix_pageviews_device_type'), 'pageviews', ['device_type'], unique=False)
    op.create_index(op.f('ix_pageviews_id'), 'pageviews', ['id'], unique=False)
    op.create_index(op.f('ix_pageviews_timestamp'), 'pageviews', ['timestamp'], unique=False)
    op.create_index(op.f('ix_pageviews_visitor_hash'), 'pageviews', ['visitor_hash'], unique=False)
    op.create_index(op.f('ix_pageviews_website_id'), 'pageviews', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pageviews_website_id'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_visitor_hash'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_timestamp'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_id'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_device_type'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_country'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_browser'), table_name='pageviews')
    op.drop_index('idx_pageviews_website_visitor', table_name='pageviews')
    op.drop_index('idx_pageviews_website_timestamp', table_name='pageviews')
    op.drop_table('pageviews')
    op.drop_index(op.f('ix_websites_user_email'), table_name='websites')
    op.drop_index(op.f('ix_websites_tracking_code'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_sessions_user_email'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
