"""index tuning: drop redundant, add hot-path composites

Revision ID: a5ddac8aaee7
Revises: 0b0c26172b8b
Create Date: 2026-09-03 00:32:07.436088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5ddac8aaee7'
down_revision = '0b0c26172b8b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_custom_events_event_timestamp', table_name='custom_events')
    op.create_index('idx_custom_events_website_visitor', 'custom_events', ['website_id', 'visitor_hash'], unique=False)
    op.create_index('idx_goal_conversions_website_visitor', 'goal_conversions', ['website_id', 'visitor_hash'], unique=False)
    op.drop_index('ix_pageviews_browser', table_name='pageviews')
    op.drop_index('ix_pageviews_country', table_name='pageviews')
    op.drop_index('ix_pageviews_device_type', table_name='pageviews')
    op.drop_index('ix_pageviews_timestamp', table_name='pageviews')
    op.drop_index('ix_pageviews_visitor_hash', table_name='pageviews')
    op.drop_index('ix_pageviews_website_id', table_name='pageviews')
    op.create_index('idx_pageviews_website_path_time', 'pageviews', ['website_id', 'path', 'timestamp'], unique=False)
    op.drop_index('idx_revenue_website_currency', table_name='revenue_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_revenue_website_currency', 'revenue_transactions', ['website_id', 'currency'], unique=False)
    op.drop_index('idx_pageviews_website_path_time', table_name='pageviews')
    op.create_index('ix_pageviews_website_id', 'pageviews', ['website_id'], unique=False)
    op.create_index('ix_pageviews_visitor_hash', 'pageviews', ['visitor_hash'], unique=False)
    op.create_index('ix_pageviews_timestamp', 'pageviews', ['timestamp'], unique=False)
    op.create_index('ix_pageviews_device_type', 'pageviews', ['device_type'], unique=False)
    op.create_index('ix_pageviews_country', 'pageviews', ['country'], unique=False)
    op.create_index('ix_pageviews_browser', 'pageviews', ['browser'], unique=False)
    op.drop_index('idx_goal_conversions_website_visitor', table_name='goal_conversions')
    op.drop_index('idx_custom_events_website_visitor', table_name='custom_events')
    op.create_index('idx_custom_events_event_timestamp', 'custom_events', ['event_name', 'timestamp'], unique=False)
    # ### end Alembic commands ###
