"""password auth + verification code fields

Revision ID: 0b0c26172b8b
Revises: c425cf957370
Create Date: 2026-09-03 00:23:02.056422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b0c26172b8b'
down_revision = 'c425cf957370'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pending_code_hash', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('pending_code_expires_at', sa.DateTime(timezone=True), nullable=True))
    # server_default so the NOT NULL add succeeds on tables with existing rows
    op.add_column('users', sa.Column('pending_code_attempts', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pending_code_attempts')
    op.drop_column('users', 'pending_code_expires_at')
    op.drop_column('users', 'pending_code_hash')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
