"""baseline schema (all tables, post-purge)

Revision ID: c425cf957370
Revises: 
Create Date: 2026-09-03 00:05:47.471149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c425cf957370'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_logs_email_type'), 'email_logs', ['email_type'], unique=False)
    op.create_index(op.f('ix_email_logs_id'), 'email_logs', ['id'], unique=False)
    op.create_index(op.f('ix_email_logs_sent_at'), 'email_logs', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_logs_to_email'), 'email_logs', ['to_email'], unique=False)
    op.create_table('used_magic_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_used_magic_tokens_id'), 'used_magic_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_used_magic_tokens_jti'), 'used_magic_tokens', ['jti'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_index(op.f('ix_sessions_user_email'), 'sessions', ['user_email'], unique=False)
    op.create_table('websites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('tracking_code', sa.String(length=255), nullable=False),
    sa.Column('verification_token', sa.String(length=64), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_reports_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_reports_frequency', sa.String(length=20), nullable=True),
    sa.Column('email_reports_recipient', sa.String(length=255), nullable=True),
    sa.Column('email_reports_day', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('public_share_token', sa.String(length=32), nullable=True),
    sa.Column('public_password_hash', sa.String(length=255), nullable=True),
    sa.Column('public_password_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('verification_token')
    )
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_index(op.f('ix_websites_email_reports_enabled'), 'websites', ['email_reports_enabled'], unique=False)
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_index(op.f('ix_websites_is_verified'), 'websites', ['is_verified'], unique=False)
    op.create_index(op.f('ix_websites_public_share_token'), 'websites', ['public_share_token'], unique=True)
    op.create_index(op.f('ix_websites_tracking_code'), 'websites', ['tracking_code'], unique=True)
    op.create_index(op.f('ix_websites_user_email'), 'websites', ['user_email'], unique=False)
    op.create_table('alert_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('spike_threshold', sa.Float(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('alert_email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_settings_id'), 'alert_settings', ['id'], unique=False)
    op.create_index(op.f('ix_alert_settings_website_id'), 'alert_settings', ['website_id'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_tokens_token', 'api_tokens', ['token'], unique=False)
    op.create_index(op.f('ix_api_tokens_id'), 'api_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_api_tokens_token'), 'api_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_api_tokens_website_id'), 'api_tokens', ['website_id'], unique=False)
    op.create_table('custom_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('path', sa.String(length=2048), nullable=True),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_custom_events_event_timestamp', 'custom_events', ['event_name', 'timestamp'], unique=False)
    op.create_index('idx_custom_events_website_event', 'custom_events', ['website_id', 'event_name'], unique=False)
    op.create_index('idx_custom_events_website_timestamp', 'custom_events', ['website_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_custom_events_country'), 'custom_events', ['country'], unique=False)
    op.create_index(op.f('ix_custom_events_event_name'), 'custom_events', ['event_name'], unique=False)
    op.create_index(op.f('ix_custom_events_id'), 'custom_events', ['id'], unique=False)
    op.create_index(op.f('ix_custom_events_timestamp'), 'custom_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_custom_events_website_id'), 'custom_events', ['website_id'], unique=False)
    op.create_table('ecommerce_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('revenue', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tax', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('shipping', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('product_category', sa.String(length=255), nullable=True),
    sa.Column('product_brand', sa.String(length=255), nullable=True),
    sa.Column('product_variant', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='ecommerce_currency_valid'),
    sa.CheckConstraint("event_type IN ('view_item', 'add_to_cart', 'remove_from_cart', 'begin_checkout', 'add_payment_info', 'add_shipping_info', 'purchase', 'refund')", name='ecommerce_event_type_valid'),
    sa.CheckConstraint('revenue IS NULL OR revenue >= 0', name='ecommerce_revenue_positive'),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ecommerce_revenue_queries', 'ecommerce_events', ['website_id', 'event_type', 'timestamp'], unique=False)
    op.create_index('idx_ecommerce_website_timestamp', 'ecommerce_events', ['website_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_country'), 'ecommerce_events', ['country'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_currency'), 'ecommerce_events', ['currency'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_device_type'), 'ecommerce_events', ['device_type'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_event_type'), 'ecommerce_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_id'), 'ecommerce_events', ['id'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_product_id'), 'ecommerce_events', ['product_id'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_timestamp'), 'ecommerce_events', ['timestamp'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_transaction_id'), 'ecommerce_events', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_visitor_hash'), 'ecommerce_events', ['visitor_hash'], unique=False)
    op.create_index(op.f('ix_ecommerce_events_website_id'), 'ecommerce_events', ['website_id'], unique=False)
    op.create_index('uq_ecommerce_purchase_txn', 'ecommerce_events', ['website_id', 'transaction_id'], unique=True, postgresql_where=sa.text("event_type = 'purchase' AND transaction_id IS NOT NULL"))
    op.create_table('funnels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funnels_id'), 'funnels', ['id'], unique=False)
    op.create_index(op.f('ix_funnels_website_id'), 'funnels', ['website_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goals_website_event', 'goals', ['website_id', 'event_name'], unique=False)
    op.create_index(op.f('ix_goals_id'), 'goals', ['id'], unique=False)
    op.create_index(op.f('ix_goals_website_id'), 'goals', ['website_id'], unique=False)
    op.create_table('pageviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('utm_source', sa.String(length=255), nullable=True),
    sa.Column('utm_medium', sa.String(length=255), nullable=True),
    sa.Column('utm_campaign', sa.String(length=255), nullable=True),
    sa.Column('utm_content', sa.String(length=255), nullable=True),
    sa.Column('utm_term', sa.String(length=255), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('scroll_depth', sa.Integer(), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pageviews_properties', 'pageviews', ['properties'], unique=False, postgresql_using='gin')
    op.create_index('idx_pageviews_website_timestamp', 'pageviews', ['website_id', 'timestamp'], unique=False)
    op.create_index('idx_pageviews_website_visitor', 'pageviews', ['website_id', 'visitor_hash'], unique=False)
    op.create_index(op.f('ix_pageviews_browser'), 'pageviews', ['browser'], unique=False)
    op.create_index(op.f('ix_pageviews_country'), 'pageviews', ['country'], unique=False)
    op.create_index(op.f('ix_pageviews_device_type'), 'pageviews', ['device_type'], unique=False)
    op.create_index(op.f('ix_pageviews_id'), 'pageviews', ['id'], unique=False)
    op.create_index(op.f('ix_pageviews_timestamp'), 'pageviews', ['timestamp'], unique=False)
    op.create_index(op.f('ix_pageviews_visitor_hash'), 'pageviews', ['visitor_hash'], unique=False)
    op.create_index(op.f('ix_pageviews_website_id'), 'pageviews', ['website_id'], unique=False)
    op.create_table('revenue_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('product_name', sa.String(length=500), nullable=True),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('visitor_id', sa.String(length=255), nullable=True),
    sa.Column('path', sa.String(length=2000), nullable=True),
    sa.Column('referrer', sa.String(length=2000), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_revenue_website_currency', 'revenue_transactions', ['website_id', 'currency'], unique=False)
    op.create_index('idx_revenue_website_timestamp', 'revenue_transactions', ['website_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_revenue_transactions_id'), 'revenue_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_revenue_transactions_transaction_id'), 'revenue_transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_revenue_transactions_visitor_id'), 'revenue_transactions', ['visitor_id'], unique=False)
    op.create_index(op.f('ix_revenue_transactions_website_id'), 'revenue_transactions', ['website_id'], unique=False)
    op.create_table('website_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'viewer', name='memberrole'), nullable=False),
    sa.Column('invited_by', sa.String(length=255), nullable=False),
    sa.Column('invited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('pending', 'active', 'revoked', name='memberstatus'), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['invited_by'], ['users.email'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_website_user_unique', 'website_members', ['website_id', 'user_email'], unique=True)
    op.create_index(op.f('ix_website_members_id'), 'website_members', ['id'], unique=False)
    op.create_index(op.f('ix_website_members_invite_token'), 'website_members', ['invite_token'], unique=True)
    op.create_index(op.f('ix_website_members_user_email'), 'website_members', ['user_email'], unique=False)
    op.create_index(op.f('ix_website_members_website_id'), 'website_members', ['website_id'], unique=False)
    op.create_table('funnel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funnel_id', sa.Integer(), nullable=False),
    sa.Column('visitor_id', sa.String(length=255), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=2000), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['funnel_id'], ['funnels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_funnel_step', 'funnel_events', ['funnel_id', 'step_number'], unique=False)
    op.create_index('idx_funnel_timestamp', 'funnel_events', ['funnel_id', 'timestamp'], unique=False)
    op.create_index('idx_funnel_visitor', 'funnel_events', ['funnel_id', 'visitor_id'], unique=False)
    op.create_index(op.f('ix_funnel_events_funnel_id'), 'funnel_events', ['funnel_id'], unique=False)
    op.create_index(op.f('ix_funnel_events_id'), 'funnel_events', ['id'], unique=False)
    op.create_index(op.f('ix_funnel_events_session_id'), 'funnel_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_funnel_events_visitor_id'), 'funnel_events', ['visitor_id'], unique=False)
    op.create_table('goal_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goal_conversions_goal_timestamp', 'goal_conversions', ['goal_id', 'timestamp'], unique=False)
    op.create_index('idx_goal_conversions_website_timestamp', 'goal_conversions', ['website_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_goal_conversions_goal_id'), 'goal_conversions', ['goal_id'], unique=False)
    op.create_index(op.f('ix_goal_conversions_id'), 'goal_conversions', ['id'], unique=False)
    op.create_index(op.f('ix_goal_conversions_timestamp'), 'goal_conversions', ['timestamp'], unique=False)
    op.create_index(op.f('ix_goal_conversions_website_id'), 'goal_conversions', ['website_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_conversions_website_id'), table_name='goal_conversions')
    op.drop_index(op.f('ix_goal_conversions_timestamp'), table_name='goal_conversions')
    op.drop_index(op.f('ix_goal_conversions_id'), table_name='goal_conversions')
    op.drop_index(op.f('ix_goal_conversions_goal_id'), table_name='goal_conversions')
    op.drop_index('idx_goal_conversions_website_timestamp', table_name='goal_conversions')
    op.drop_index('idx_goal_conversions_goal_timestamp', table_name='goal_conversions')
    op.drop_table('goal_conversions')
    op.drop_index(op.f('ix_funnel_events_visitor_id'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_session_id'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_id'), table_name='funnel_events')
    op.drop_index(op.f('ix_funnel_events_funnel_id'), table_name='funnel_events')
    op.drop_index('idx_funnel_visitor', table_name='funnel_events')
    op.drop_index('idx_funnel_timestamp', table_name='funnel_events')
    op.drop_index('idx_funnel_step', table_name='funnel_events')
    op.drop_table('funnel_events')
    op.drop_index(op.f('ix_website_members_website_id'), table_name='website_members')
    op.drop_index(op.f('ix_website_members_user_email'), table_name='website_members')
    op.drop_index(op.f('ix_website_members_invite_token'), table_name='website_members')
    op.drop_index(op.f('ix_website_members_id'), table_name='website_members')
    op.drop_index('idx_website_user_unique', table_name='website_members')
    op.drop_table('website_members')
    op.drop_index(op.f('ix_revenue_transactions_website_id'), table_name='revenue_transactions')
    op.drop_index(op.f('ix_revenue_transactions_visitor_id'), table_name='revenue_transactions')
    op.drop_index(op.f('ix_revenue_transactions_transaction_id'), table_name='revenue_transactions')
    op.drop_index(op.f('ix_revenue_transactions_id'), table_name='revenue_transactions')
    op.drop_index('idx_revenue_website_timestamp', table_name='revenue_transactions')
    op.drop_index('idx_revenue_website_currency', table_name='revenue_transactions')
    op.drop_table('revenue_transactions')
    op.drop_index(op.f('ix_pageviews_website_id'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_visitor_hash'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_timestamp'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_id'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_device_type'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_country'), table_name='pageviews')
    op.drop_index(op.f('ix_pageviews_browser'), table_name='pageviews')
    op.drop_index('idx_pageviews_website_visitor', table_name='pageviews')
    op.drop_index('idx_pageviews_website_timestamp', table_name='pageviews')
    op.drop_index('idx_pageviews_properties', table_name='pageviews', postgresql_using='gin')
    op.drop_table('pageviews')
    op.drop_index(op.f('ix_goals_website_id'), table_name='goals')
    op.drop_index(op.f('ix_goals_id'), table_name='goals')
    op.drop_index('idx_goals_website_event', table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_funnels_website_id'), table_name='funnels')
    op.drop_index(op.f('ix_funnels_id'), table_name='funnels')
    op.drop_table('funnels')
    op.drop_index('uq_ecommerce_purchase_txn', table_name='ecommerce_events', postgresql_where=sa.text("event_type = 'purchase' AND transaction_id IS NOT NULL"))
    op.drop_index(op.f('ix_ecommerce_events_website_id'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_visitor_hash'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_transaction_id'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_timestamp'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_product_id'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_id'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_event_type'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_device_type'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_currency'), table_name='ecommerce_events')
    op.drop_index(op.f('ix_ecommerce_events_country'), table_name='ecommerce_events')
    op.drop_index('idx_ecommerce_website_timestamp', table_name='ecommerce_events')
    op.drop_index('idx_ecommerce_revenue_queries', table_name='ecommerce_events')
    op.drop_table('ecommerce_events')
    op.drop_index(op.f('ix_custom_events_website_id'), table_name='custom_events')
    op.drop_index(op.f('ix_custom_events_timestamp'), table_name='custom_events')
    op.drop_index(op.f('ix_custom_events_id'), table_name='custom_events')
    op.drop_index(op.f('ix_custom_events_event_name'), table_name='custom_events')
    op.drop_index(op.f('ix_custom_events_country'), table_name='custom_events')
    op.drop_index('idx_custom_events_website_timestamp', table_name='custom_events')
    op.drop_index('idx_custom_events_website_event', table_name='custom_events')
    op.drop_index('idx_custom_events_event_timestamp', table_name='custom_events')
    op.drop_table('custom_events')
    op.drop_index(op.f('ix_api_tokens_website_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_id'), table_name='api_tokens')
    op.drop_index('idx_api_tokens_token', table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_alert_settings_website_id'), table_name='alert_settings')
    op.drop_index(op.f('ix_alert_settings_id'), table_name='alert_settings')
    op.drop_table('alert_settings')
    op.drop_index(op.f('ix_websites_user_email'), table_name='websites')
    op.drop_index(op.f('ix_websites_tracking_code'), table_name='websites')
    op.drop_index(op.f('ix_websites_public_share_token'), table_name='websites')
    op.drop_index(op.f('ix_websites_is_verified'), table_name='websites')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_email_reports_enabled'), table_name='websites')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_sessions_user_email'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_used_magic_tokens_jti'), table_name='used_magic_tokens')
    op.drop_index(op.f('ix_used_magic_tokens_id'), table_name='used_magic_tokens')
    op.drop_table('used_magic_tokens')
    op.drop_index(op.f('ix_email_logs_to_email'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_sent_at'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_id'), table_name='email_logs')
    op.drop_index(op.f('ix_email_logs_email_type'), table_name='email_logs')
    op.drop_table('email_logs')
    # ### end Alembic commands ###
